### ISSUE TITLE
[FEATURE] S1 On-boarding help

### ISSUE THREAD

**Issue by codeman02** [VATSIMCanada/issue-tracker#6] opened 2022-12-30 13:14 UTC
**Is your feature request related to a problem? Please describe.**
There is a re-occurring theme in the membership help channels in discord where controllers who just passed their S1 exam don't understand that it takes the system up to 24h to process the rating.  A huge piece to this is with me to update the on-boarding/welcome CBT's but I think we can attack this a few more ways as eager students will 5000% skip that information.  

**Describe the solution you'd like**
1)  For the S1 exam it would be ideal at the end after a pass for a message to be shown in bold on the summary page.
2)  FAQ page:  "I have just passed the S1 exam, why am I still an observer?" 
2)  Discord bot to have a command for when people miss the CBT and Notification to reply to those who feel the need to spam the membership help channels. 

**Additional context**
Verbiage:  Welcome to VATCAN. Please note that once you have passed the S1/Entrance Exam it can take up to 24 hours for your rating to be applied. Please check back on MyVATCAN for your rating to show "S1" before proceeding to the next step of choosing an FIR to transfer into. If after 24 hours your rating has not updated please submit a support ticket.

**Comment by JordannDev** [comment] 2023-01-09 17:48
The root cause of this issue should be fixed with some larger changes being implemented soon, the display changes can absolutely be made, I'll update once they have been implemented.

**Comment by mgwalsh99** [comment] 2024-02-05 13:26
I believe that this has been resolved?

**Comment by xLostShadows** [comment] 2024-02-19 17:18
I believe so

**Closed as completed by xLostShadows** 2024-02-19 17:18 UTC
Labels: Report: Feature Request
