### ISSUE TITLE
[BUG] CZAE S1 Exam - Assigning to Transfered Students

### ISSUE THREAD

**Issue by codeman02** [VATSIMCanada/issue-tracker#5] opened 2022-12-27 00:30 UTC
**Describe the bug**
Brad Crockett from Vancouver has a student (David Bradley - 1519118) who transferred from VATUK. Because David is an S1 he did not have to do our CZAE S1 test,  however Brad wants to have the student do the test to get a benchmark on their Canada ops.  Whenever the student is assigned the exam it will show up as assigned then disappear within 10 minutes.   I had tried to assign the test and same thing it will show up in the pending list then disappear. I suspect its because they are already a S1 so perhaps we need to spawn a copy of the test for instructors to assign to transferred students at their behest. 

**To Reproduce**
1. Go to Exams
2. Click on by CID 1519118  and CZAE S1 and assign
3. See Pending page 
4. wait ...  check again 

**Expected behavior**
As above it would be handy to have this test in a state where we can assign it to transferred students. 

**Additional context**
Thank you so much :D 
![Capture1](https://user-images.githubusercontent.com/16567600/209590484-9a23fd71-6842-4fc0-a911-89e301965536.PNG)

**Comment by JordannDev** [comment] 2022-12-27 18:30
@codeman02 This is likely because the website was never intended to have S1 Exams assigned manually, this was intended to be an automated process, I'd be willing to bet there is a check somewhere to see if the person who assigned the exam is the same CID as the student.

I'll see if we can locate the bug and figure out where this is coming from

**Comment by xLostShadows** [comment] 2023-11-27 20:03
I will add automation to this. Will add code that detects when a user has been transferred from CZZN and is already an S1 and will receive the S1 exam automatically.

**Comment by mgwalsh99** [comment] 2024-02-05 13:16
This is no longer allowed/permitted with the change in Vatsim policies.

**Closed as completed by mgwalsh99** 2024-02-05 13:16 UTC
Labels: Report: Bug
